server:
 port: 8089
spring:
 application:
  name: analytics-service
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/
jwt:
 secret: medicore-super-secret-key-change-in-production-min-256-bits!!
