server:
  port: 8080
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth
          uri: lb://auth-service
          predicates: [Path=/auth/**]
        - id: patients
          uri: lb://patient-service
          predicates: [Path=/patients/**]
        - id: doctors
          uri: lb://doctor-service
          predicates: [Path=/doctors/**]
        - id: appointments
          uri: lb://appointment-service
          predicates: [Path=/appointments/**]
        - id: billing
          uri: lb://billing-service
          predicates: [Path=/billing/**]
        - id: pharmacy
          uri: lb://pharmacy-service
          predicates: [Path=/pharmacy/**]
        - id: notifications
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
            - Path=/ws/**
        - id: admin
          uri: lb://patient-service
          predicates: [Path=/admin/**]
        - id: nurse
          uri: lb://nurse-service
          predicates: [Path=/nurse/**]
        - id: analytics
          uri: lb://analytics-service
          predicates: [Path=/analytics/**]
        - id: symptom
          uri: lb://symptom-check-service
          predicates: [Path=/symptom-check/**]
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:3000"
              - "http://127.0.0.1:5173"
            allowedMethods: ["GET","POST","PUT","PATCH","DELETE","OPTIONS"]
            allowedHeaders: ["*"]
            allowCredentials: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
jwt:
  secret: ${JWT_SECRET:medicore-super-secret-key-change-in-production-min-256-bits!!}
